---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao
  namespace: openbao
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: openbao
data:
  config.hcl: |
    ui = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/openbao/data"
    }

    # Auto-unseal using Kubernetes secrets
    seal "transit" {
      address = "http://openbao.openbao.svc.cluster.local:8200"
      disable_renewal = "false"

      key_name = "autounseal"
      mount_path = "transit/"

      # Use Kubernetes auth for transit seal
      tls_skip_verify = "true"
    }

    # API address
    api_addr = "http://openbao.openbao.svc.cluster.local:8200"
    cluster_addr = "http://openbao.openbao.svc.cluster.local:8201"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
  namespace: openbao
  labels:
    app: openbao
spec:
  serviceName: openbao
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      serviceAccountName: openbao
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
      containers:
      - name: openbao
        image: quay.io/openbao/openbao:latest
        imagePullPolicy: IfNotPresent
        command:
        - bao
        - server
        - -config=/openbao/config/config.hcl
        env:
        - name: BAO_ADDR
          value: "http://127.0.0.1:8200"
        - name: SKIP_SETCAP
          value: "true"
        ports:
        - name: http
          containerPort: 8200
          protocol: TCP
        - name: internal
          containerPort: 8201
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/sys/health?standbyok=true
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /openbao/data
        - name: config
          mountPath: /openbao/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: openbao-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: truenas-iscsi
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: openbao
  labels:
    app: openbao
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: internal
    port: 8201
    targetPort: 8201
    protocol: TCP
  selector:
    app: openbao
