---
# ConfigMap with unseal script
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-unseal-script
  namespace: openbao
data:
  unseal.sh: |
    #!/bin/sh

    # Get seal status (works even when sealed)
    STATUS=$(wget -qO- http://127.0.0.1:8200/v1/sys/seal-status 2>/dev/null)

    if [ -z "$STATUS" ]; then
      exit 0  # Not ready yet, exit gracefully
    fi

    echo "Checking if OpenBao is sealed..."
    SEALED=$(echo "$STATUS" | grep -o '"sealed":[^,]*' | cut -d: -f2)

    if [ "$SEALED" = "true" ]; then
      echo "OpenBao is sealed, unsealing..."

      # Unseal with 3 keys (threshold)
      wget -qO- --post-data "{\"key\":\"$UNSEAL_KEY_1\"}" \
        --header "Content-Type: application/json" \
        http://127.0.0.1:8200/v1/sys/unseal >/dev/null 2>&1

      wget -qO- --post-data "{\"key\":\"$UNSEAL_KEY_2\"}" \
        --header "Content-Type: application/json" \
        http://127.0.0.1:8200/v1/sys/unseal >/dev/null 2>&1

      wget -qO- --post-data "{\"key\":\"$UNSEAL_KEY_3\"}" \
        --header "Content-Type: application/json" \
        http://127.0.0.1:8200/v1/sys/unseal >/dev/null 2>&1

      echo "OpenBao unsealed successfully!"
    else
      echo "OpenBao is already unsealed."
    fi
---
# Job to apply the unseal keys secret (run once after applying this file)
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-openbao-unseal-keys
  namespace: openbao
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: openbao
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - |
          kubectl apply -f /secrets/openbao-unseal-keys.sops.yaml
      restartPolicy: Never
