---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-cert
  namespace: media
spec:
  dnsNames:
    - plex.internal.sever-it.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: plex-tls-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-cert
  namespace: media
spec:
  dnsNames:
    - overseerr.internal.sever-it.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: overseerr-tls-cert
