apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      priorityClassName: workload-normal  # Can be preempted by system-critical if needed
      runtimeClassName: nvidia
      hostNetwork: true  # Required for Plex discovery
      containers:
      - name: plex
        image: linuxserver/plex:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: VERSION
          value: "docker"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        ports:
        - containerPort: 32400
          name: plex
          protocol: TCP
        - containerPort: 1900
          name: dlna-udp
          protocol: UDP
        - containerPort: 5353
          name: discovery-udp
          protocol: UDP
        - containerPort: 8324
          name: roku
          protocol: TCP
        - containerPort: 32410
          name: gdm-1
          protocol: UDP
        - containerPort: 32412
          name: gdm-2
          protocol: UDP
        - containerPort: 32413
          name: gdm-3
          protocol: UDP
        - containerPort: 32414
          name: gdm-4
          protocol: UDP
        - containerPort: 32469
          name: dlna-tcp
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
            nvidia.com/gpu: "1"
          limits:
            memory: "3Gi"
            cpu: "4000m"
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: media-storage
          mountPath: /config
          subPath: plex
        - name: media-storage
          mountPath: /tv
          subPath: tv
          readOnly: true
        - name: media-storage
          mountPath: /movies
          subPath: movies
          readOnly: true
        - name: media-storage
          mountPath: /transcode
          subPath: plex-transcode
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
  - name: plex
    port: 32400
    targetPort: 32400
    protocol: TCP
