apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 8989
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: media-storage
          mountPath: /config
          subPath: sonarr
        - name: media-storage
          mountPath: /downloads
          subPath: downloads
        - name: media-storage
          mountPath: /tv
          subPath: tv
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
  - name: http
    port: 8989
    targetPort: 8989
    protocol: TCP
