apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token3
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:tPAIBSk3hhuyxtqCvgYChxWbm8l8QFTqoXpJwdrxzzOmdYbmBWps2g==,iv:N6+VFmu4/ubllBBWZ1BFmyBLfAUPblhN+ZucEkrQex4=,tag:i2uDQ7skfpqeyRlQb5p7iQ==,type:str]
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRFkzakwwQU9hZW4xYThw
            WGJGQTVTakNLa2RORVZsazdPYUhJZGJxVmpNClRUdVFja2o5UVQ2ZXlNYkZDZDZq
            RGdXTG04NVNQSUtxT3UzakdIbThBYkEKLS0tIEc3b083ZlVhb1I3Tjk0WnZpUlo4
            S0Z6TGpoKzlUdWVpdVdrWWJ6UTdUWVEKLmVcDrw6Mcql7ofwWgOkO2Kmy4l1fu2H
            bzfJoSqxRfS48wLYjx8OdrfSYHQNOHRF3O6ReAREevu+KQj0E1IsmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T18:53:49Z"
    mac: ENC[AES256_GCM,data:XUkiws4jKB9EHua5rIlwOv5FfiLD9CuHoLiqvfJNJK1SgCbaHCmqNeczYq9zOlxTi0UXuFRC/g1+04xzLMJQRKAjKXAIRL4uBQqXTSqQKKanlugMLvm8nB5bD2oMmBDEHaQ+RUCFt8FCSA6SEpGdrTqDb9n8Tgdi074aUp1Rj3g=,iv:10hEMyGsf66dVDD/lMAyuPLiAc6NDi6BF19vmcjf3JQ=,tag:6ifKyVDuZic7OYpeubxg3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
