apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.1.6
    helm:
      values: |
        configs:
          cm:
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

        repoServer:
          extraVolumes:
            - name: sops-age
              secret:
                secretName: sops-age

          extraVolumeMounts:
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true

          extraEnv:
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/.config/sops/age/keys.txt
          volumes:
            - name: custom-tools
              emptyDir: {}

          initContainers:
            - name: install-ksops
              image: viaductoss/ksops:v4.3.3
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Installing KSOPS...";
                  mv ksops /custom-tools/;
                  mv kustomize /custom-tools/;
                  echo "Done.";
              volumeMounts:
                - mountPath: /custom-tools
                  name: custom-tools

          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

