apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.1.6
    helm:
      values: |
        configs:
          cm:
            # Allow kustomize exec/alpha plugins (needed for ksops generator)
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

        repoServer:
          # 1) Volumes: plugin dir + age key
          volumes:
            - name: ksops-plugins
              emptyDir: {}
            - name: sops-age
              secret:
                secretName: sops-age

          # 2) Mount them into repo-server
          volumeMounts:
            - name: ksops-plugins
              mountPath: /custom-plugins
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true

          # 3) Env: tell kustomize where plugins live, and sops where age key is
          env:
            - name: KUSTOMIZE_PLUGIN_HOME
              value: "/custom-plugins"
            - name: SOPS_AGE_KEY_FILE
              value: "/home/argocd/.config/sops/age/keys.txt"
            # optional, but shuts up XDG-related warnings:
            - name: XDG_CONFIG_HOME
              value: "/home/argocd/.config"

          # 4) InitContainer: create plugin dir and symlink ksops into it
          initContainers:
            - name: setup-ksops-plugin
              image: viaductoss/ksops:v4.3.3
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -ex
                  # Create the plugin directory structure
                  mkdir -p /custom-plugins/viaduct.ai/v1/ksops
                  # Symlink the ksops binary that already exists in /usr/local/bin
                  cp /usr/local/bin/ksops /custom-plugins/viaduct.ai/v1/ksops/ksops
                  chmod +x /custom-plugins/viaduct.ai/v1/ksops/ksops
              volumeMounts:
                - name: ksops-plugins
                  mountPath: /custom-plugins

  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
