apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.1.6
    helm:
      values: |
        configs:
          cm:
            # Allow kustomize exec/alpha plugins
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

        repoServer:
          # Use the ksops-enabled repo-server image
          image:
            repository: viaductoss/ksops
            tag: v4.3.3
            # (you can pin to a version you’re comfortable with)

          # Mount the age key so sops can decrypt
          volumes:
            - name: sops-age
              secret:
                secretName: sops-age

          volumeMounts:
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true

          env:
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/.config/sops/age/keys.txt
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
