apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.1.6
    helm:
      values: |
        configs:
          cm:
            # Allow kustomize exec/alpha plugins (needed for ksops)
            kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

        repoServer:
          # Use ksops-enabled repo-server image
          image:
            repository: viaductoss/ksops
            tag: v4.3.3   # or v4.4.0; 4.3.3 is non-distroless and easier to debug

          # Mount your age key secret
          volumes:
            - name: sops-age
              secret:
                secretName: sops-age

          volumeMounts:
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true

          env:
            # CRITICAL: ksops/kustomize use XDG_CONFIG_HOME for plugin discovery
            - name: XDG_CONFIG_HOME
              value: "/.config"

            # Tell sops where your age private key is
            - name: SOPS_AGE_KEY_FILE
              value: "/home/argocd/.config/sops/age/keys.txt"
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
