apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-iscsi
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.iscsi
                storageClasses:
                    - name: truenas-iscsi
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: ext4
                volumeSnapshotClasses:
                    - name: truenas-iscsi
                driver:
                    config:
                        driver: freenas-iscsi
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:yiwrNmFGsd4TdItCLvvTxdjY81IG3BhsmNDbDH3OlS9jUKJAe9jp1EZlNOsbizqLZwmToyRIhzWSn6HsOF3u+MXO,iv:AxwXSCtXxH29UQ4XyfUKqUqgYaSqtLI30/O6aIXGHFw=,tag:v6HApC6AsntXqurKXGnGGQ==,type:str]
                            allowInsecure: true
                        sshConnection:
                            host: 192.168.2.30
                            port: 22
                            username: root
                            privateKey: ENC[AES256_GCM,data:OvlprQ6hfHGNEBZfS74IKHNT66BYUeiOxDzVfD711q6vzZCr6eW4/bJ6AytcoCILQz/yZY7H/FeCsmQ+zA9vIwz+5QStN2YiuMp7FXaC9vR0XILuN61yzrT6CZT1NsdLTl2XR8c0NJJcTykiwmL7gNiUeSchvxQR7GyDAvsriNyul8Y+wCPCcuGFV2DzWHekvuuWqN55hOloIhZe6W/TKP3tS+O/Qfb/YRIIljVeVd4X1wbpdlecuVDN5UEYc5tNJ0vL7assENGpjMtxfxYr2a2v6Pb+a3RPwCsGO4tWU5lJ2dfSHT8HVwdFZQCVfmfOzBioNoRqo2HimeB/xnuBZWnUjZCOmBXyr9FevO6ypkW+udtrqNP6mNbAHmw/kkDogaf8K6ii8fAAj/b0ouGUPfqp5Ox7RbaEFMj0GYsMsh36heaCZ35LlWRZOnaTS0JiBZQBUKZJ9nTbbH1iuFdRBbLTrwiPYgs1JD8lClDbntFbG/eSjNSa6m3gyNK/s4k7CG29YphjjMiRZXS0HpesMbYDAbCkxponph5V2V8M0Bx6uTI=,iv:mM5VngnOdOCvk4slX6DHsqc0y/LyqNQU0DjVxqDv7r4=,tag:WCj36TD+O7msAlZwKAt7Eg==,type:str]
                        zfs:
                            cli:
                                sudoEnabled: false
                                paths:
                                    zfs: /usr/sbin/zfs
                                    zpool: /usr/sbin/zpool
                                    sudo: /usr/bin/sudo
                                    chroot: /usr/sbin/chroot
                            datasetParentName: default/k8s-pv/iscsi
                            detachedSnapshotsDatasetParentName: default/k8s-pv/iscsi-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        iscsi:
                            targetPortal: 192.168.2.30:3260
                            namePrefix: csi-
                            nameSuffix: -talos
                            targetGroups:
                                - targetGroupPortalGroup: 1
                                  targetGroupInitiatorGroup: 1
                                  targetGroupAuthType: None
                            extentInsecureTpc: true
                            extentXenCompat: false
                            extentDisablePhysicalBlocksize: true
                            extentBlocksize: 512
                            extentRpm: SSD
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYmMxaXJwN3QvSVZLV3ha
            aTB3aHJTRzlMTHJIMTJMUWVXblpzNEQ3bTEwCkpPQ1BoSHVHcVVpYXNvaEVhR3Bv
            YmZvalQrdE9oeUpvbmNRQUlJM0lKaXcKLS0tIHZqVjBYcjBxMHZEZ2Fwam9WMHpN
            Z1UxVHJxRDhLZmxrUmFrcW8xcmJUTTQKEN3FSVdnOzmyH5aqRUohmbniYVqCWTgJ
            hF8U6TfS9OwJIjT1B1mLtGlkKSItmbXh2wEpwJgTiVbIxvTP/Z/n5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T20:24:47Z"
    mac: ENC[AES256_GCM,data:8cx0oBpHZWv83Vww9Yxw/FKOJH6TddAPXFlqoat6ZTDVOAhgQFGOyaE1HomYHm52fsCDV9iNwfZksqdFvmtWmywU2PToxDZZ+5HcmyYTuIreGdRO1HGAyIk+aGr9lfr9Bm4L0bjMf9htsVdQrx5Z83FLZw1PeAxFXDHTndLH0O0=,iv:ielsDT1WyRv/eudkex7Q++2Oze+yADB9rLt8OESCq44=,tag:RJ/8GRK/NBYMr6VxV5KoBw==,type:str]
    encrypted_regex: ^(data|stringData|apiKey|privateKey)$
    version: 3.11.0
