apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-nfs
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.nfs
                storageClasses:
                    - name: truenas-nfs
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: nfs
                      mountOptions:
                        - nfsvers=4
                        - nolock
                        - soft
                volumeSnapshotClasses:
                    - name: truenas-nfs
                driver:
                    config:
                        driver: freenas-api-nfs
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:2O3uoxSv3K/F7+zJXsPV209ZnAKZKJkWZ+uLB3P1BaCbmLUeZIjDXJyS3aVqJIzD+NDWCy1SoI5YKHH/553KLhGH,iv:6FDjsCBsJfM3HjK6MkqdGsehpkjuKHrtsl1B+u4sP6U=,tag:SKtJRWwlkOSyTB1r5EXkXg==,type:str]
                            allowInsecure: true
                        zfs:
                            datasetParentName: default/smb-share
                            detachedSnapshotsDatasetParentName: default/smb-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        nfs:
                            shareHost: 192.168.2.30
                            shareAlldirs: false
                            shareAllowedHosts: []
                            shareAllowedNetworks: []
                            shareMaprootUser: root
                            shareMaprootGroup: root
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNUdpZ0pkbnBwbHBTSjZ1
            djVNbndtLzFoOWg5ZXBwTnBjN3RPelpxQ2hBCkFjellzckVHcGVYY0JhMU5zYVk1
            TjNrUm4xL0EvVFA3RkVZa2c1bmhaTU0KLS0tIEFTbmdWUXJPOWtnVHVZOXRnMWRl
            OVJ6UFd1UXdLbHdMSjFDS3p0QVpzUTAKlo9OKzwH7tjh+FlsHAaoy1rsyOLQkTXD
            IKZZqCh7WtqInBIgVFf2txTfpHJuBxNynIIgzteA+NnzNSolvIIbhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:19:03Z"
    mac: ENC[AES256_GCM,data:7uVDmA+Y5NWwts5+eSh5Iqhm0B4f816bxhHMtyk9l8B7OzeMZ7F2/H4EGNHcORIq8WcbDg7XVgLPeK6e9wBWlBqsYVdNl2Aho9+lfJVCrjMuUEWhnP9BcD7sWSE67tUSLKt8PM/41dTCHo5zCX+1QB5ftID3jFTQK2YSPlBhcCU=,iv:i5KxPd57UldLcHutirSVKG1kRVg0UFyHTVg19BPRhgk=,tag:7UCAu0sz/S1OvqraxzGHbw==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
