apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-iscsi
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.iscsi
                storageClasses:
                    - name: truenas-iscsi
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: ext4
                volumeSnapshotClasses:
                    - name: truenas-iscsi
                driver:
                    config:
                        driver: freenas-api-iscsi
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:bMgJPzlxec66ODoa70tzi6hGPcc3Z+MSkgzWX6UTZZfK1YqqIuZunUYLbLzVU5GjLiwm7E63xUc9zdKCquDa5ozp,iv:6TAm5xDyYGrigThFzqV/yfewCUzwm42kfr4e5m5EKNM=,tag:JguOBbwG2blW5YeTDdNG1w==,type:str]
                            allowInsecure: true
                        zfs:
                            datasetParentName: default/k8s-pv/talos-iscsi-share
                            detachedSnapshotsDatasetParentName: default/k8s-pv/talos-iscsi-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        iscsi:
                            targetPortal: 192.168.2.30:3260
                            namePrefix: csi-
                            nameSuffix: -talos
                            targetGroups:
                                - targetGroupPortalGroup: 1
                                  targetGroupInitiatorGroup: 1
                                  targetGroupAuthType: None
                            extentInsecureTpc: true
                            extentXenCompat: false
                            extentDisablePhysicalBlocksize: true
                            extentBlocksize: 512
                            extentRpm: SSD
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWEp4TkJOanZ4Y3pQdTIz
            Z25UYmVyNzB5cWlZeTFMWm43azI3ZzYxUVU4Ck93czZWV3VETU1PeEtVdDlXQmlw
            L1hWUEZrMHFQWXpUZ2JpQ2Njc24wTHcKLS0tIEc4RXBZT1Z0TmtJZkx6aFRiQkdI
            bm9kaVIrbFBFc1FUc0MzenM3ZmFkK2MKFmn9psFerEQEi+huVWbucv0S4Yli5aj+
            za4Xy9Wg6jZGbiUb0D4lPdYYCpZBptGBZFe3n3YCh8awsoOUlEegnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:12:43Z"
    mac: ENC[AES256_GCM,data:dRZ29/anjcnA5VRiaQ63ZyQsYEdjuBkZIJ24FO2ttRM3Vmc87bTs2Bi9Gm70WdvOFh89j7ANevP4/Kx0G/+QBL9RGlXTSUyQx20DBOKJGCDudYRcxErgpEXlqcZ81zHGXzwRchtFlZb89sgCIRxIJYLFcVxvhcmE1plYKVX9tPw=,iv:hFGhTA15Ge2QrDR72ZR2Yt8NRIgWcbZrBfim7iQ3MmM=,tag:xl6TRykE64lYV1ZrAdNhxw==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
