apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-iscsi
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.iscsi
                storageClasses:
                    - name: truenas-iscsi
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: ext4
                volumeSnapshotClasses:
                    - name: truenas-iscsi
                driver:
                    config:
                        driver: freenas-api-iscsi
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:VP2Tk2L0EgG3COZf1SV4nQnmBFP06NQ1NXY2lo4D6Rbx+YDWTlysvm4GFMVOn/JTwqCckVEQZUF9yS52W25iyNKp,iv:Snn/SMLgrBSExSVkVVf6kp+GudkNau2YA2Hoo7XeWGc=,tag:KrdVWw2pUawZ7LS+q3Js4w==,type:str]
                            allowInsecure: true
                        zfs:
                            datasetParentName: default/k8s-pv/talos-iscsi-share
                            detachedSnapshotsDatasetParentName: default/k8s-pv/talos-iscsi-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        iscsi:
                            targetPortal: 192.168.2.30:3260
                            namePrefix: csi-
                            nameSuffix: -talos
                            targetGroups:
                                - targetGroupPortalGroup: 1
                                  targetGroupInitiatorGroup: 1
                                  targetGroupAuthType: None
                            extentInsecureTpc: true
                            extentXenCompat: false
                            extentDisablePhysicalBlocksize: true
                            extentBlocksize: 512
                            extentRpm: SSD
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL1hhTFZ0d0NhajRQSDlT
            LzNHZnE1K3ZxQmxNTnJuaWZpT0MrUlBiN0RRCnkwMnpmSE9jWElZMnJpRzMwYytO
            OTJzcnVYSENMR2UrRDBiVUxHUmt5QU0KLS0tIE5raGhzbDhRUzd3azg4Q3FtSXZD
            ZXdpRHRzekpvNTFJQlcvUlpoOWRCMkUKbbpmZjT7SXxGxk9quVXVryUAypJp7/vK
            zwJjrXPDUHBTUP9tun1faaiJWfftwnP7iFpOfzlrD2m4jvdHJnbFhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:19:01Z"
    mac: ENC[AES256_GCM,data:yCxpBnruyEq3HjWSjmayeAJP1vqIGoVEb+WFTP6D+jwIw6S7K0LXeIDgNwIBm7nPnC28zJR/AamEtmRoCneESSxFfrXUj62K4cQfNc14Vwy8XwUPqH/aauEH4VmpaqVAHxR9bRriZexJ6eFRaKigSFjw/zmu3GkeYVbnUetGqQM=,iv:aEi6YPfhgO9hzLAB+GGHIX8qsUhEI1ePuNs55wujHcs=,tag:wKjvmqKyAGk0dlWnYmBraQ==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
