apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-nfs
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.nfs
                storageClasses:
                    - name: truenas-nfs
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: nfs
                      mountOptions:
                        - nfsvers=4
                        - nolock
                        - soft
                volumeSnapshotClasses:
                    - name: truenas-nfs
                driver:
                    config:
                        driver: freenas-nfs
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:/LqrDGGhmgI4LyB0lXT6BVSO9U9adoUr7F0DdeT5NfuW1a6lIQ9nk4b5fZLYVxz85+BroGjQTMj1aiO55LE8Utzy,iv:Apr036uahPg5QSMlOCySTeuFLmh5Tr89aPxtJ/8mW24=,tag:ZVNvhpQJj/oGBfheTw4H6A==,type:str]
                            allowInsecure: true
                        sshConnection:
                            host: 192.168.2.30
                            port: 22
                            username: root
                            privateKey: ENC[AES256_GCM,data:QJF2U1PQFw+tKuNoGQPJx3L23UftvoDgF/6LluVzAvEjBbBhDbRyyZooAexvIKSx9B/xaGUB+mW7eyTbj1pAk19BTbCG+LzjbAHXrYYJ7rKG6z0RPV7oNMYLhERYupgoPZzlyth5ChrPOQHpZfNXvtx04kM8HsgQqBFIcdtUBQAFOONp2qS3zB9kLh5rdTqYSBTW3DdNGettqT5HBF+YBO1lXtmwgr5DkatBMFukNR3szb/jtAq/e56iog/9QLAfS+nCJ90D/We23y6eg8i9jZA0tMYKzSEdAsiMbcXFz07x8hJekYi4WFEivt7W8nMNLm9ReH0lkOF6fbhDyX2cbNa3dU13fQg4+iRlmL2ev6188yFIt8Q4TGU+Z5ekDIxSb0UE7PIStBrjtMo3iqxVbkhhZpnlJXorJgtSEH7sFwuhz1d0rrAD4pW1bpGoXzwq9cY+Zu0IL2su1SSa4nYmu6312UceZlhiKuDAjcsxeckuEZVMO8WJLkmEGdbAR52WfZPvbtiXTGnDGUqN+6UB7gHL9iMgP3zNkmOSkvafKOqYWM0=,iv:Km7uyXvME7VgA/p//yAEbNlROVGr2muetwzHmDR43UI=,tag:F680IxqmOWq8tuDhHBtADw==,type:str]
                        zfs:
                            cli:
                                sudoEnabled: false
                                paths:
                                    zfs: /usr/sbin/zfs
                                    zpool: /usr/sbin/zpool
                                    sudo: /usr/bin/sudo
                                    chroot: /usr/sbin/chroot
                            datasetParentName: default/smb-share
                            detachedSnapshotsDatasetParentName: default/smb-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        nfs:
                            shareHost: 192.168.2.30
                            shareAlldirs: false
                            shareAllowedHosts: []
                            shareAllowedNetworks: []
                            shareMaprootUser: root
                            shareMaprootGroup: root
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUVlBcUg2NEFtbWNySDVQ
            ZlA2c050UWdhQnZ0VExoM2ZKZW1heHlhZFdvCmpzcVAzNml0NXJRUUYzOGpIRXpj
            QkFrbmNyc2JyVXVrL1Z2Unl5a2l5T1UKLS0tIEMyRTZpRVJsS3h2T1p3TzQwdlFo
            dUNMc2ZjRTF3WVR5dzh2dEdTd25IRDgKa/vtK/aHQZPcU2YAW9zf29eoAwV4YGkb
            W9eMkVF0VAvFr5L3A4t1M5HDgcnQQ+6HW43casCDQh7z5jaq6OOX9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T20:24:47Z"
    mac: ENC[AES256_GCM,data:zeO6cFtNyNY5N5LtOM9RIRbhNJfqnNSdl13I6jJFR9rZZO+iJFJ1lf1a/vv73bicHrSgthR1nOcyjh8FRJnn20FWEM20rxTj6cQnOSfzvGhmmadtDcgHqeBeeuUmajSt4PRwemoFR0RVsuJ+gHCybVkATVBmZ0KucUfTpkIxegE=,iv:lHz0BWqFWIfKk40RX48qY8IkkaJMLEgZ6S1RL/nq844=,tag:yZ9aYsfxCGyTjtrOVNbSDQ==,type:str]
    encrypted_regex: ^(data|stringData|apiKey|privateKey)$
    version: 3.11.0
