apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-iscsi
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.iscsi
                storageClasses:
                    - name: truenas-iscsi
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: ext4
                volumeSnapshotClasses:
                    - name: truenas-iscsi
                driver:
                    config:
                        driver: truenas-api-iscsi
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:5OdSrGuZx+Q0zJOYwJIC542BiZ4i38bhSAMTxGJmAFYGVPDghQuhqVU6/1TJ0YK5yUdjIJj9Or1KmpwONfldC1ow,iv:YarOMEUx/N8fl12HACJ3wr4rRTqwQEgiF/UPsBDT0Rk=,tag:+Ux0MJsFSDZ6D6t/irB9bg==,type:str]
                            allowInsecure: true
                        zfs:
                            datasetParentName: default/k8s-pv/talos-iscsi-share
                            detachedSnapshotsDatasetParentName: default/k8s-pv/talos-iscsi-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        iscsi:
                            targetPortal: 192.168.2.30:3260
                            namePrefix: csi-
                            nameSuffix: -talos
                            targetGroups:
                                - targetGroupPortalGroup: 1
                                  targetGroupInitiatorGroup: 1
                                  targetGroupAuthType: None
                            extentInsecureTpc: true
                            extentXenCompat: false
                            extentDisablePhysicalBlocksize: true
                            extentBlocksize: 512
                            extentRpm: SSD
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2NRUUg3Y3E2ZHZBditD
            RHhMdTc4c1VvWm9DZGc5cGcxajNJQ1poRVg0CnNIZkRvSE4yTk5wMG40SlZIek9I
            azlWdHVoRGxzdmlaUFdZRmlnMGtQalUKLS0tIEloRmcxSFFVTFErWStpVzR2d0hi
            SlViK3pPM3ZWTHZJV29xTDd2cVZwM00K3NBWXZ7WMFHsYVO8wVAtfaTgzgK3cTWP
            ptAybuZergNVwsmKjyla3lXXymgY2B4nvbx9Xz1z1tvlEIHcBbAkpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T05:36:22Z"
    mac: ENC[AES256_GCM,data:k5CTvecgcKiYZx8RqXNR+cGzonGbSOV9/WRRuDU2jVKNaTMJja1aH5DdmZvJUe4AypBfnaW6WOIKOH0cKl/s1ZFr1ursDkMbGec/vAJxeMZ61L248yv1r/XE59oPziRhROmxPyGlX9sNTO98UNEYVQOmg9oV+CnSvt3hpTVUYdk=,iv:AJ/5Cf3WwngIkIVvZNM1Fo6n0/hp+1C/MhU86fe6+2E=,tag:K9hcT2W8hePZFUUE/2NGcg==,type:str]
    encrypted_regex: ^(data|stringData|apiKey)$
    version: 3.11.0
