apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: democratic-csi-nfs
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.14.7
        helm:
            valuesObject:
                csiDriver:
                    name: org.democratic-csi.nfs
                storageClasses:
                    - name: truenas-nfs
                      defaultClass: false
                      reclaimPolicy: Delete
                      volumeBindingMode: Immediate
                      allowVolumeExpansion: true
                      parameters:
                        fsType: nfs
                      mountOptions:
                        - nfsvers=4
                        - nolock
                        - soft
                volumeSnapshotClasses:
                    - name: truenas-nfs
                driver:
                    config:
                        driver: freenas-nfs
                        httpConnection:
                            protocol: https
                            host: 192.168.2.30
                            port: 443
                            apiKey: ENC[AES256_GCM,data:4yEBX/UAd3dcqbUZIhMFXXq0mcdn+KyaZJiQcKvmTQGwja66Jl3dZ1gWQZF7r0St7+wwmgm0AqaIXXw5FCGzyrOv,iv:Tz0ieZz89vaKpMSV8RD3arnANBWWH5TRhrvkjoEAFt0=,tag:oIshu2ZDJoZ3eF5ov3LsAA==,type:str]
                            allowInsecure: true
                        sshConnection:
                            host: 192.168.2.30
                            port: 22
                            username: root
                            privateKey: ENC[AES256_GCM,data:Wd52DFoPragmWX8Jj9LvM0HMwFAtoMZ7aBCQlmBDw6q55X3lUDq4JcFhcipoHllzV9ML1mxKMWKWZzLszLjDn2foarJFOKw8+Q7vvN0vHyYhGN/1EQNSs/F1D3mW/+DWLgWAtuyLtWE6R3NJmphKypARwb/O1TBg0ReUfhj54/iRFiErgHh/7n1lL4rPJVoYDGv6bcAqNKQTtg4GFY9vwgZz2IygcSbvWIVoTm0jAr92wqyzkMRVySeOQ7vfar4wDJIM/n8AI3r8gTHyZ57J1aJOq7cJA2CE9GHqx4FODMdMp0CA0KQ+T6GiqERVKiFDBDDXROdoFpq78Z+VNnj7f8jShY4A8KNUKVgr7/o1ljBobMaIC1ZJqwyXLQxYZuJwpdVl6qKz/dVzsM5jvKGgVeILoYz238jl7D2K6e+xjong1OhgDAHaaJqq7GXZlnPROqFuCOr/V3luqQWpunl8dV6AfKvrTDIMEHTQcgwr1FN2JKkzPM0KqLT4uuA52AwE+hJ4z3KqXHYNNaeiEWUrmeB1IQVBl5YcgfKOyPPPERPzURw=,iv:zDkbogz5y1jIW5ocG2/sjbTgoPpnM2Q5ndvfJozS6hU=,tag:yrKRvMOj0JuHv1BmGzX9PA==,type:str]
                        zfs:
                            cli:
                                sudoEnabled: false
                                paths:
                                    zfs: /usr/sbin/zfs
                                    zpool: /usr/sbin/zpool
                                    sudo: /usr/bin/sudo
                                    chroot: /usr/sbin/chroot
                            datasetParentName: default/smb-share
                            detachedSnapshotsDatasetParentName: default/smb-share-snapshots
                            datasetEnableQuotas: true
                            datasetEnableReservation: false
                            datasetPermissionsMode: "0770"
                            datasetPermissionsUser: 0
                            datasetPermissionsGroup: 0
                        nfs:
                            shareHost: 192.168.2.30
                            shareAlldirs: false
                            shareAllowedHosts: []
                            shareAllowedNetworks: []
                            shareMaprootUser: root
                            shareMaprootGroup: root
    destination:
        server: https://kubernetes.default.svc
        namespace: democratic-csi
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
sops:
    age:
        - recipient: age1033ld5gtn23xsz9lateded3kpssp62hkhjq9vs3jza3ad63uggnsqw5xhd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdlJIa0Z4S09CRTRLRWRo
            OC93cjNSdnlNREplQ2M5Z09XbmQyL3BqcmpRCkVKUGcrbnNaM2tkSmpvVnRldXdw
            VHNoYWxXWlhVbHFlTUN5WTdRL2JJdXcKLS0tIFk1dlJrbVZCNEJvanpiSTl5bTl6
            N1BSNjR4QXZMQmhlb2YrMGRVc25VRWcKsE8jhOdeFpuK0OLJtG2aBqNBEHm9me/M
            1WEz1kW0akYRIEwvpCBwtBE0kJh1HyiTkNQQ90b53PpmP3x0kseY2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T18:07:13Z"
    mac: ENC[AES256_GCM,data:S4dJbrofDHXG6HSDxBIcGXf4Zuwc+T2zyHHlNG2Tv+M2vvayGO0R9Kn986fh4laMohHwN124o1jzuM3s7o5mhEw3UNnBdXAjwwkjUmCgkoixWxrAZ3NGD1sqgrYekJ2cXtlQI1xvTYH8JP36o6o5A6iQs0LQLAT2+NQQtv3pgJM=,iv:rL0VwFzEUjxvHeo2ykXxFjy1NMSm+yyfPZKrK/gElxo=,tag:2ok+vUptX/fK1EKowWCqgQ==,type:str]
    encrypted_regex: ^(data|stringData|apiKey|privateKey)$
    version: 3.11.0
