apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dmwoods38/homelab-gitops.git
    targetRevision: main
    path: platform/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Note: Enable automated sync after kube-prometheus-stack is installed
    # automated:
    #   prune: true
    #   selfHeal: true
